name: ubuntu-latest
run-name: build and test my program
on: [push]
jobs:
    build-and-run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: seanmiddleditch/gha-setup-ninja@master
            - run: make clean & make build
