name: build1
run-name: build and test my program
on: [push]
jobs:
    build-and-run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: seanmiddleditch/gha-setup-ninja@master
            - uses: ilammy/msvc-dev-cmd@v1
            - uses: Bacondish2023/setup-googletest@v1
              with:
                tag: v1.14.0
            - run: make clean & make build
